export const imagesData = [
  {
    id: 1,
    imagesUrl: [
      'https://bit.ly/2Z4KKcF',
      './1.png',
      './2.png',
      './2.png',
      './2.png',
      './2.png',
      './2.png',
      './2.png',
    ],
    address: 'Pioneertown, California',
    distance: '96 miles away',
    duration: '5 nights, · Sep 8 – 13',
    price: 3121,
    rating: 4.94,
  },
  {
    id: 2,
    imagesUrl: ['https://bit.ly/2Z4KKcF', './1.png', './2.png'],
    address: 'Pioneertown, California',
    distance: '96 miles away',
    duration: '5 nights, · Sep 8 – 13',
    price: 3121,
    rating: 4.94,
  },
  {
    id: 3,
    imagesUrl: ['https://bit.ly/2Z4KKcF', './1.png', './2.png'],
    address: 'Pioneertown, California',
    distance: '96 miles away',
    duration: '5 nights, · Sep 8 – 13',
    price: 3121,
    rating: 4.94,
  },
  {
    id: 4,
    imagesUrl: ['https://bit.ly/2Z4KKcF', './1.png', './2.png'],
    address: 'Pioneertown, California',
    distance: '96 miles away',
    duration: '5 nights, · Sep 8 – 13',
    price: 3121,
    rating: 4.94,
  },
  {
    id: 5,
    imagesUrl: ['https://bit.ly/2Z4KKcF', './1.png', './2.png'],
    address: 'Pioneertown, California',
    distance: '96 miles away',
    duration: '5 nights, · Sep 8 – 13',
    price: 3121,
    rating: 4.94,
  },
  {
    id: 6,
    imagesUrl: ['https://bit.ly/2Z4KKcF', './1.png', './2.png'],
    address: 'Pioneertown, California',
    distance: '96 miles away',
    duration: '5 nights, · Sep 8 – 13',
    price: 3121,
    rating: 4.94,
  },
  {
    id: 7,
    imagesUrl: ['https://bit.ly/2Z4KKcF', './1.png', './2.png'],
    address: 'Pioneertown, California',
    distance: '96 miles away',
    duration: '5 nights, · Sep 8 – 13',
    price: 3121,
    rating: 4.94,
  },
  {
    id: 8,
    imagesUrl: ['https://bit.ly/2Z4KKcF', './1.png', './2.png'],
    address: 'Pioneertown, California',
    distance: '96 miles away',
    duration: '5 nights, · Sep 8 – 13',
    price: 3121,
    rating: 4.94,
  },
];
